entity_embed.settings:
  type: mapping
  label: 'Entity embed settings'
  mapping:
    upload_directory:
      type: string
      label: 'Upload directory for buton images'

entity_embed.embed_button.*:
  type: config_entity
  label: 'Embed button config'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    button_label:
      type: string
      label: 'Button label'
    entity_type:
      type: string
      label: 'Entity type'
    icon_fid:
      type: integer
      label: 'Button image'
