entity_embed.settings:
  type: config_object
  label: 'Entity embed settings'
  mapping:
    file_scheme:
      type: string
      label: 'File scheme for button images'
    upload_directory:
      type: string
      label: 'Upload directory for button images'

entity_embed.embed_button.*:
  type: config_entity
  label: 'Embed button config'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    entity_type:
      type: string
      label: 'Entity type'
    entity_type_bundles:
      type: sequence
      label: 'Entity type bundles'
      sequence:
        type: string
        label: 'Bundle'
    button_icon_uuid:
      type: string
      label: 'Button image'
    display_plugins:
      type: sequence
      label: 'Allowed display plugins'
      sequence:
        type: string
        label: 'Display plugin'
